# -*- coding: utf-8 -*-
"""Assignment_plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RI5nVBtVr_EH3SJ0wJLilhFer6ov3O2T

# <Center> Assignmnet Plotly 3rd March

# Q1:- Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a scatter plot for age and fare columns in the titanic dataset.
"""

import seaborn as sn
titanic = sn.load_dataset('titanic')
titanic

import plotly as plt
import plotly.express as px
fig= px.scatter(titanic,x='age', y='fare')
fig.show()

"""# Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

tips = plt.data.tips()

tips

fig1 = px.box(tips, y= 'total_bill')
fig1.show()



"""#Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day" column with the color parameter."""



fig2 = px.histogram(tips, x='sex', y = 'total_bill', pattern_shape= 'smoker', color = 'day')
fig2.show()



"""# Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for the color parameter.
Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
dimensions parameter.
"""

iris = plt.data.iris()

iris

fig4 = px.scatter_matrix(iris,color='species',dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"])
fig4.show()

Q5. What is Distplot? Using Plotly express, plot a distplot.

"""# Q5. What is Distplot? Using Plotly express, plot a distplot.

Ans :- Distplot is a graphical representation of the distribution of a dataset. It provides a histogram along with a kernel density estimate (KDE) plot, which shows the estimated probability density function of the variable.


To create a distplot using Plotly express in Python, we need to import the necessary libraries and load a dataset. Here's an example:
"""

import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="total_bill", y="tip", color="sex",
                   marginal="box", # or violin, rug
                   hover_data=df.columns)
fig.show()



"""# <center> End of Assignment"""

